# Generated by Django 5.0.6 on 2024-06-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='phone',
            field=models.BigIntegerField(default=123),
        ),
    ]
